# ===============================
# DATABASE
# ===============================
spring:
  datasource:
    # servermode = AUTO_SERVER. for connecting console
    url: jdbc:h2:./testdb/h2;MODE=MYSQL;DB_CLOSE_ON_EXIT=false;AUTO_SERVER=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 200
      max-lifetime: 10000
  flyway:
    user: sa
    password: password
    url: jdbc:h2:./testdb/h2;MODE=MYSQL;DB_CLOSE_ON_EXIT=false;AUTO_SERVER=TRUE
    # to make schema history table
    baseline-on-migrate: true
    # ignore order
    out-of-order: true
  web:
    resources:
      static-locations: classpath:/static, file:/git/azusato/azusato/resources/test-resources
    