# ===============================
# DATABASE
# ===============================
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/azusato_test
    username: admin
    password: password
  flyway:
    user: admin
    password: password
    url: jdbc:mysql://localhost:3306/azusato_test
    locations: classpath:db/test-migration
    # to make schema history table
    baseline-on-migrate: true
    # ignore order
    out-of-order: true
  web:
    resources:
      static-locations: classpath:/static, file:/git/azusato/azusato/resources/test-resources
  test:
    database:
      # DataJpaTestを使うとき、初期h2DBを使わずこの設定のDataSourceを利用する。
      replace: none
      
logging:
  level:
    root: DEBUG
      
celebration:
  # お祝いテーブルのコンテンツパスが保持されるサーバーのフォルダ位置
  server-content-folder-path: /git/azusato/azusato/test-resources

profile:
  # サーバーからするとの基本イメージの格納場所
  server-default-image-folder-path: src\main\resources\static\image\default\profile
  # クライアントの本イメージのファイルの格納場所
  client-image-folder-path: /git/azusato/azusato/test-resources
  
wedding:
  division-datetime: 2023-05-01