# ===============================
# DATABASE
# ===============================
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/azusato
    username: admin
    password: password
  flyway:
    user: admin
    password: password
    url: jdbc:mysql://localhost:3306/azusato
    # to make schema history table
    baseline-on-migrate: true
    # ignore order
    out-of-order: true
  web:
    resources:
      static-locations: classpath:/static, file:/git/resources
  #jpa:
    #hibernate:
     #ddl-auto: update
      
celebration:
  # お祝いテーブルのコンテンツパスが保持されるサーバーのフォルダ位置
  server-content-folder-path: /git/resources/celebration/content      
      
profile:
  # サーバーからするとの基本イメージの格納場所
  server-default-image-folder-path: src\main\resources\static\image\default\profile
  # クライアントの本イメージのファイルの格納場所
  client-image-folder-path: /git/resources
  
# クライアントに関する設定  
client:
  origin: http://localhost:8081
